server:
  port: 8080

spring:
  redis:
    database: 0
    host: 114.96.82.155
    timeout: 10000
    port: 6379
    password: redisadmin
    lettuce:
      pool:
        max-wait: -1
        max-active: 8
        max-idle: 8
        min-idle: 0
